deployments:
  site1:
    auth_key: AUTH_KEY
    remote:
      url: http://localhost
      endpoint: /deploy.php
      target: /home/user/app
      temp_dir: /home/user/tmp
      history_dir: /home/user/tmp/old_deployments

    local:
      path: .
      temp_dir: /tmp

    ignore:
      - .git*
      - deployment.*
      - *.log
      - temp/*
      - deploy
      - bower_components
      - node_modules
      - .idea

    extra_files:
      'deploy/env_file': .env

    before_scripts:
      - composer install --no-dev